tailwind.config = {
        darkMode: "class",
        theme: {
          extend: {
            "colors": {
                    "on-primary-container": "#636562",
                    "secondary-container": "#394857",
                    "tertiary-fixed-dim": "#c6c6c6",
                    "on-tertiary": "#2f3131",
                    "on-tertiary-container": "#636465",
                    "on-secondary-fixed-variant": "#394857",
                    "on-primary-fixed-variant": "#454745",
                    "surface-bright": "#393939",
                    "surface-variant": "#353535",
                    "surface-container-high": "#2a2a2a",
                    "on-surface": "#e4e2e1",
                    "surface-tint": "#c6c7c3",
                    "secondary": "#b8c8da",
                    "tertiary": "#ffffff",
                    "error-container": "#93000a",
                    "on-secondary-fixed": "#0d1d2a",
                    "on-secondary-container": "#a7b7c8",
                    "tertiary-fixed": "#e3e2e2",
                    "primary": "#ffffff",
                    "on-error": "#690005",
                    "surface-dim": "#131313",
                    "surface-container-low": "#1b1c1c",
                    "background": "#131313",
                    "secondary-fixed-dim": "#b8c8da",
                    "tertiary-container": "#e3e2e2",
                    "inverse-surface": "#e4e2e1",
                    "surface-container-highest": "#353535",
                    "primary-fixed-dim": "#c6c7c3",
                    "on-tertiary-fixed-variant": "#464747",
                    "inverse-primary": "#5d5f5c",
                    "secondary-fixed": "#d4e4f6",
                    "on-tertiary-fixed": "#1a1c1c",
                    "on-background": "#e4e2e1",
                    "outline": "#8f928d",
                    "on-primary-fixed": "#1a1c1a",
                    "surface-container": "#1f2020",
                    "surface-container-lowest": "#0e0e0e",
                    "on-primary": "#2f312e",
                    "outline-variant": "#444844",
                    "on-surface-variant": "#c5c7c2",
                    "error": "#ffb4ab",
                    "primary-fixed": "#e2e3df",
                    "on-secondary": "#223240",
                    "primary-container": "#e2e3df",
                    "surface": "#131313",
                    "inverse-on-surface": "#303030",
                    "on-error-container": "#ffdad6"
            },
            "borderRadius": {
                    "DEFAULT": "0.25rem",
                    "lg": "0.5rem",
                    "xl": "0.75rem",
                    "full": "9999px"
            },
            "spacing": {
                    "unit": "4px",
                    "container-max": "1440px",
                    "gutter": "16px",
                    "margin": "24px"
            },
            "fontFamily": {
                    "body-md": ["Inter"],
                    "label-mono": ["Inter"],
                    "h1": ["Inter"],
                    "h2": ["Inter"],
                    "body-sm": ["Inter"],
                    "body-lg": ["Inter"],
                    "h3": ["Inter"],
                    "label-caps": ["Inter"]
            },
            "fontSize": {
                    "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
                    "label-mono": ["11px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "500"}],
                    "h1": ["40px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
                    "h2": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600"}],
                    "body-sm": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}],
                    "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
                    "h3": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}],
                    "label-caps": ["12px", {"lineHeight": "1", "letterSpacing": "0.1em", "fontWeight": "700"}]
            }
          },
        },
      }